name: Build Python package

on: push

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up Python (latest)
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Install system_calls
      run: python3 -m pip install dist/system_calls-*.whl --user

    - name: Install pytest
      run: python3 -m pip install pytest --user

    - name: Run pytest
      run: pytest -v system_calls/tests/test*.py

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
