name: Generate system calls HTML table

on:
  pull_request:
    branches: [ "master" ]

jobs:
  generate-html:
    name: Generate system calls HTML table
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        # we need templates/common
        with:
          submodules: true

      - name: Set up Python (latest)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install 'system calls' package
        run: |
          pip install .

      - name: Generate system calls HTML
        run: |
          # Store in path used on Github Pages
          mkdir -p out/syscalls-table
          python3 examples/generate-html-table.py > out/syscalls-table/syscalls.html
