name: Upload HTML table to Github Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate system calls HTML table"]
    types:
      - completed

jobs:
  deploy-to-pages:
    name: Upload HTML table to Github Pages
    # only if generation of HTML worked
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
      pages: write
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from HTML Generator
        uses: actions/download-artifact@v4
        with:
          name: syscalls-html-page
          path: out/
          # Use the run_id of the workflow that just completed
          run-id: ${{ github.event.workflow_run.id }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
